name: 'build-test'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
    Inputs:
      changelogs:
        required: true
        default: '*Whats New:*\n• Added Changelogs to Testflight\n\n*Changes:*\n• Now builds can be made without any changelogs\n\n'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          zipPath: 'Builds/BuildPackage.zip'
          zipRootName: 'BuildPackage'
          outputPath: 'XCodeProject'
          changelog: "${{ github.event.inputs.changelogs }}"
      - run: |
          cd XCodeProject
          ls
          cd ../tempPath
          ls
      
