name: 'build-test'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
    inputs:
      changelogs:
        required: true
        default: '*Whats New:*\n• Added Changelogs to Testflight\n\n*Changes:*\n• Now builds can be made without any changelogs\n\n'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create string
        run: |
          MY_STRING="${{ github.event.inputs.changelogs }}"
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
          echo $MY_STRING
          echo "::set-output name=content::$MY_STRING"
        id: string_mod
      - uses: ./
        with:
          zipPath: 'Builds/BuildPackage.zip'
          zipRootName: 'BuildPackage'
          outputPath: 'XCodeProject'
          changelog: "${{ steps.my_string.outputs.content }}"
      - run: |
          cd XCodeProject
          ls
          cd ../tempPath
          ls
      
